version: '3'

services:
  db:
    image: postgres:14.11
    ports:
      - "5454:5432"
    env_file:
      - .env
    user: ${POSTGRES_USER}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - pg-volume:/var/lib/postgresql/data

volumes:
  ypgophermart-pg-data:
    driver: local